### ISSUE TITLE
User creates recommendation

### ISSUE THREAD

**Issue by joshmcarthur** [impactoss/impactoss-server#23]
As a User

I want to create a record of a recommendation 

So that I can assign actions to it

---

Development tasks:
1. Generate Recommendation model
2. Set up model for i18n
3. Add 'Title' and No.
4. Does not include categorisation and action assignment controls as per wireframes

TODO: UPDATE WIREFRAME SCREENSHOT FROM https://projects.invisionapp.com/share/FA9B8R625#/screens/204745964
<img width="966" alt="screenshot 2016-08-08 15 04 07" src="https://cloud.githubusercontent.com/assets/292020/17468187/62caadde-5d79-11e6-9648-18bc4ff4f228.png">

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#4
