### ISSUE TITLE
User creates action

### ISSUE THREAD

**Issue by joshmcarthur** [impactoss/impactoss-server#24]
As a user

I want to create an action

So that I have recorded government actions that need to take place, are taking place or have taken place

---

Development tasks:
1. Generate Action model 
2. Set up action model for i18n
3. Add title, description, ~~start date and~~ target date attributes to model
4. Implement action form minus categorisation, recommendation, and indicator associations as per wireframe
5. Saving the action takes the user to the list of actions
6. Failure to save shows form errors
7. Successful saves shows success message

**Comment by tmfrnz** [comment]
This issue was moved to dumparkltd/hr-nmrf-client#5
