### ISSUE TITLE
Bookmark custom views

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-server#323]
To allow storing user-specific bookmarks, we will need the creation of a new model and table "bookmarks" 

Like the other models, it should be a "VersionedRecord" (see https://github.com/impactoss/impactoss-server/blob/master/app/models)

The table should have the following columns (in addition to the common "updated_at" and "created_at")

- id [PK]: the bookmark id (automatically assigned by db)
- user_id [FK]: the user id as stored in the users table
- view: an object storing the view parameters (see below for details)
- title: the bookmark name 

(it is not needed to make sure title and view are unique for each user)

The bookmark model thus belongs to the user model

See for the related issue https://github.com/nmrf/sadata/issues/43

**Comment by tmfrnz** [comment]
To work with the bookmarks from the client we will need the following endpoints:

### GET

For retrieving a list of user bookmarks for a given user.

Endpoint: /bookmarks/[user-id]

Conditions: 
- user has to be authenticated 
- user can only retrieve a list of his own bookmarks (regardless of role)

### POST

For creating a bookmark.

Endpoint: /bookmarks

Payload: 
- title
- view (see below for parameters)

(user id should be derivable from the current session)

Conditions:
- user has to be authenticated 

### PUT 

To update a bookmark

Endpoint: /bookmarks/[id]

Payload: 
- title

(it is not possible to change the view itself)

Conditions: 
- user has to be authenticated 
- bookmark must belong to that user

### DELETE

To delete a bookmark

Endpoint: /bookmarks/[id]

Conditions: 
- user has to be authenticated 
- bookmark must belong to that user

**Comment by tmfrnz** [comment]
The client application will derive the view parameters from the specific view URL. The parameters should be the following:

General 

- type: the entity list type (eg 'recommendations', or 'actions') 

Filters

- categories: a list of category ids (each category has a unique category id so no need to store the taxonomy)
- without_taxonomy: a list of taxonomy ids 
- connected_categories: a list of objects, each consisting of the following attributes
  - category_id 
  - entity_type (eg 'recommendations', or 'actions') 
- connections: a list of objects, each consisting of
  - type: the entity type (eg 'recommendations', or 'actions') 
  - id: the entity id 
- attributes: a list of objects, each consisting of
  - attribute (e.g. "draft", "accepted")
  - attribute value
  
Grouping information

- group: taxonomy id for main grouping
- subgroup: taxonomy id for secondary grouping

Sorting information
- sort: the sort parameter
- order: the sort order

Other
- expand: level of expansion for nested items (0, 1 or 2)

No need to store current page and pages per view information.

As an example, for the URL 

`https://demo.impactoss.org/actions?catx=sdgtargets%3A87&where=draft%3Afalse&connected=indicators%3A279&order=desc&cat=176&expand=2&sort=updated_at&subgroup=5&group=6`

we would expect the following view object
```
{
  type: 'actions'
  subgroup: 5,
  group: 6,
  expand: 2,
  categories: [ 176 ],
  connected_categories: [{
    type: 'sdgtargets',
    id: 87,
  }],
  connections: [{
    type: 'indicators',
    id: 279,
  }],
  attributes: [{
    attribute: 'draft',
    value: 'false'
  }],
  sort: 'updated',
  order: 'desc'
}
```

**Comment by oventi** [comment]
The selectBookmark selector should not test for equal paths but for equal attributes as the order of query parameters and the presence of additional, irrelevant parameters (e.g. items per page, page number) should not matter. We should have a positive list of all relevant parameters (eg in the utils/bookmark file) to use across the different functions. This could also include the required information if they are single or multiparams (so similar to what you have done here but ideally as one list of objects), e.g.

```
const BOOKMARK_PARAMS = [
  { query: 'subgroup', type: 'single' },
  ...
  { query: 'catx', type: 'multiple' },
]
```

**Comment by oventi** [comment]
Please also add the following query params to that list
- "cat" type multiple
- "without", type multiple (as previously specified)
- "search", type single (not yet specified)

**Comment by oventi** [comment]
Please do not pass and store an empty "cat" array when no category filters are set

The view object stored is more similar to the URL structure than what was specified here (and thus not as explicit) but I am happy to keep this simpler style

The bookmark title remains in the bookmark widget even if the bookmark is no longer present (ie when I open a bookmark and change the search) - this should be removed when it becomes inactive

There appears to be a bug in the locationToBookmarkView when recreating bookmarks including multiparams. Specifically it appears that it will add an ":undefined" to the end of each query parameter (so if I bookmark e.g. this URL http://localhost:3000/actions?connected=recommendations%3A2&connected=recommendations%3A3 it will be recreated as http://localhost:3000/actions?connected=recommendations%3A2:undefined&connected=recommendations%3A3:undefined)

**Comment by oventi** [comment]
This url works fine, http://localhost:3000/actions?cat=177&connected=indicators:279&expand=2&group=6&order=desc&sort=updated_at&subgroup=5 

but this fails, http://localhost:3000/actions?cat=177&connected=indicators:279&expand=2&group=1&order=desc&sort=updated_at&subgroup=5 

the only change is the parameter group

**Comment by tmfrnz** [comment]
One more thing I came across: sometimes a list view setting can be set to a default value (eg `&expand=0` or `&group=5&subgroup=0`) which will result in the same view as not having these parameters set in the first place. As a consequence the Bookmarker (understandably) fails to identify them as equal.

So this http://localhost:3000/actions?group=5&subgroup=0&expand=0
is the same view as this http://localhost:3000/actions

Now we could either

- teach the Bookmarker to ignore default values (eg the default grouping id is set in the [taxonomies table](https://github.com/impactoss/impactoss-server/blob/master/db/schema.rb#L213) and in the client's [list config](https://github.com/impactoss/impactoss-client/blob/master/app/containers/ActionList/constants.js#L71) 
- teach the list views to never store the default values in the URL to start with

**Comment by tmfrnz** [comment]
> One more thing I came across: sometimes a list view setting can be set to a default value (eg `&expand=0` or `&group=5&subgroup=0`) which will result in the same view as not having these parameters set in the first place. As a consequence the Bookmarker (understandably) fails to identify them as equal.
> 
> So this http://localhost:3000/actions?group=5&subgroup=0&expand=0
> is the same view as this http://localhost:3000/actions
> 
> Now we could either
> 
> * teach the Bookmarker to ignore default values (eg the default grouping id is set in the [taxonomies table](https://github.com/impactoss/impactoss-server/blob/master/db/schema.rb#L213) and in the client's [list config](https://github.com/impactoss/impactoss-client/blob/master/app/containers/ActionList/constants.js#L71)
> * teach the list views to never store the default values in the URL to start with
> 
> I'd probably be in favor of the first option, especially as we only have a couple of params to fix (expand, group and subgroup)

Again the default grouping id is set in the [taxonomies table](https://github.com/impactoss/impactoss-server/blob/master/db/schema.rb#L213) and can either be 1 for 1st level grouping or 2 for 2nd level grouping or subgrouping.

Eg here the Cycle set as the default subgroup for recommendations
https://github.com/impactoss/impactoss-server/blob/master/db/seeds.rb#L55

Note that the server does not currently validate that only one taxonomy can have the 1 or the 2, however this not crucial as it is not something set by the user but during installation
