### ISSUE TITLE
Track updates to relationships in all related tables

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-server#362]
bring in the developments from advocacy-tracker-server
https://github.com/dumparkltd/advocacy-tracker-server/pull/53
https://github.com/dumparkltd/advocacy-tracker-server/pull/57

**Comment by parndt** [comment]
This was resolved by [19d5be9](https://github.com/impactoss/impactoss-server/commit/19d5be9b33c03fb51a2e1f6f8966aaeae28cddd0) and [1a46511](https://github.com/impactoss/impactoss-server/commit/1a465112214d0d2ad30ef545456a7f8ec29d3781)
