### ISSUE TITLE
Change date format in due date mailer

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-server#368]
currently the date is output in the database format `yyyy-mm-dd` but should be formatted according to the app-wide locale (in NZ: `dd/mm/yyyy` (@parndt should this be "en-GB" or "en-NZ"?))

here is where the due date object's date is passed to the views. https://github.com/impactoss/impactoss-server/blob/nz-justice-development/app/mailers/due_date_mailer.rb#L10

**Comment by tmfrnz** [comment]
not sure why but apparently those notifications are still formatted `yyyy-mm-dd`

![image](https://github.com/impactoss/impactoss-server/assets/5811956/8bd4bc2a-5525-4fe2-bc7b-07b0bae01609)

**Comment by parndt** [comment]
It's weird because the dev console gives:
```ruby
irb(main):001> I18n.l(Date.current)
=> "22/02/2024"
```

🤔
