### ISSUE TITLE
Make sure Clockwork sends emails at timezone specified and not UTC time 

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-server#372]
Currently Clockwork appears to send email notifications at the time specified but assumes UTC
https://github.com/impactoss/impactoss-server/blob/nz-justice-development/scheduler.rb

Let's make sure it uses the configured timezone 
https://github.com/impactoss/impactoss-server/blob/nz-justice-development/config/application.rb#L21

**Comment by parndt** [comment]
Hmm, this is an interesting one. Looks like we can do it:

<img width="825" alt="image" src="https://github.com/impactoss/impactoss-server/assets/10128/37cbade9-fcf2-4ed0-846c-fa0b174330af">
