### ISSUE TITLE
Send notification to Category Manager when progress report is created or subsequently edited

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-server#397]
> Generate a notification to the Category Manager when a Contributor uploads a progress report or subsequently edits the draft report.  > The notification will be sent at the end of the day so that multiple notifications resulting from multiple edits will be avoided..

**Comment by parndt** [comment]
> The notification will be sent at the end of the day

what time is the end of the day?

**Comment by parndt** [comment]
> when a Contributor uploads a progress report or subsequently edits the draft report

does this only apply to users with role `contributor`?

**Comment by tmfrnz** [comment]
> what time is the end of the day?

let's say midnight however ideally let's make this configurable and store in an environment variable

**Comment by tmfrnz** [comment]
> does this only apply to users with role contributor?

i am not entirely sure. will come back to you on this

**Comment by tmfrnz** [comment]
some additional clarification: with "uploaded" they mean "created", thus a notification is sent when a new progress report is created (is always related to an indicator)

**Comment by parndt** [comment]
@tmfrnz thanks - does this only apply to draft reports?

**Comment by tmfrnz** [comment]
> @tmfrnz thanks - does this only apply to draft reports?

to be confirmed (i think it doesn't matter much as contributors can only edit draft reports)

**Comment by tmfrnz** [comment]
client is happy as is (although we may need to tweak the wording in the future)
